[package]
authors = ["Sascha Grunert <mail@saschagrunert.de>"]
categories = ["embedded", "no-std"]
description = "A template for building applications for ARM Cortex-M7 STM32H7xx Microcontrollers"
keywords = ["arm", "cortex-m", "template"]
license = "MIT"
name = "stm32h7xx"
repository = "https://github.com/japaric/cortex-m-quickstart"
version = "0.1.0"

[[bin]]
doc = false
name = "app"
path = "src/main.rs"

[dependencies]
cortex-m = "0.4.3"
cortex-m-semihosting = "0.2.0"
alloc-cortex-m = "0.3.2"

[dependencies.cortex-m-rt]
version = "0.3.13"
features = ["abort-on-panic"]

[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
debug = true
lto = true
